// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from 'E:/sqltool-cloud/sqltool-cloud/sql-tool-frontend/node_modules/_@ant-design_icons@4.8.3@@ant-design/icons/es/icons/HomeOutlined';
import PlusOutlined from 'E:/sqltool-cloud/sqltool-cloud/sql-tool-frontend/node_modules/_@ant-design_icons@4.8.3@@ant-design/icons/es/icons/PlusOutlined';
export default { HomeOutlined, PlusOutlined };
