// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import HomeOutlined from 'D:/sqlfather-pro/sqlfather-backend/sql-tool-frontend/node_modules/_@ant-design_icons@4.8.1@@ant-design/icons/es/icons/HomeOutlined';
import PlusOutlined from 'D:/sqlfather-pro/sqlfather-backend/sql-tool-frontend/node_modules/_@ant-design_icons@4.8.1@@ant-design/icons/es/icons/PlusOutlined';
export default { HomeOutlined, PlusOutlined };
